### ISSUE TITLE
Outil « Sub_profil » : Profil MNT / MNS 

### ISSUE THREAD

**Issue by dsavary** [gusthiot/VDLTools#17]
Erreur python lors de l'utilisation : 

> TypeError: attachCurves() takes exactly 4 arguments (3 given) 
Traceback (most recent call last):
  File "C:/Users/cada0093/.qgis2/python/plugins\VDLTools\tools\subprofile_tool.py", line 149, in canvasReleaseEvent
    self.__calculateProfile()
  File "C:/Users/cada0093/.qgis2/python/plugins\VDLTools\tools\subprofile_tool.py", line 173, in __calculateProfile
    self.__dockWdg.attachCurves(None, self.__ownSettings)
TypeError: attachCurves() takes exactly 4 arguments (3 given)

**Comment by gusthiot** [comment]
Fait
