### ISSUE TITLE
Erreur suite à l’utilisation de l’outils « profil » de  VDL Tool :

### ISSUE THREAD

**Issue by dsavary** [gusthiot/VDLTools#23]
Lors de la sélection d'une autre couche ou d'un groupe dans le projet QGIS, ce message d’erreur apparaît  souvent : 

> AttributeError: 'NoneType' object has no attribute 'removeSelection' 
Traceback (most recent call last):
  File "C:/Users/cada0093/.qgis2/python/plugins\VDLTools\tools\profile_tool.py", line 129, in __closed
    self.__cancel()
  File "C:/Users/cada0093/.qgis2/python/plugins\VDLTools\tools\profile_tool.py", line 145, in __cancel
    self.__lineLayer.removeSelection()
AttributeError: 'NoneType' object has no attribute 'removeSelection'

**Comment by gusthiot** [comment]
Fait
